//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsMyDemo.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProjectDataObjectList", Namespace="http://www.ByteartRetail.com/CollectionDataObjectList.xsd", ItemName="ProjectDataObject")]
    [System.SerializableAttribute()]
    public class ProjectDataObjectList : System.Collections.Generic.List<ProductsMyDemo.ServiceReference2.ProjectDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectDataObject", Namespace="http://www.ByteartRetail.com/ProjectDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class ProjectDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActorsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsMyDemo.ServiceReference2.ContractDataObject ContractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsMyDemo.ServiceReference2.WaranteeDataObject WaranteeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsMyDemo.ServiceReference2.LoanDataObjectList LoansField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectNo {
            get {
                return this.ProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNoField, value) != true)) {
                    this.ProjectNoField = value;
                    this.RaisePropertyChanged("ProjectNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ActorsName {
            get {
                return this.ActorsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActorsNameField, value) != true)) {
                    this.ActorsNameField = value;
                    this.RaisePropertyChanged("ActorsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public ProductsMyDemo.ServiceReference2.ContractDataObject Contract {
            get {
                return this.ContractField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractField, value) != true)) {
                    this.ContractField = value;
                    this.RaisePropertyChanged("Contract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ProductsMyDemo.ServiceReference2.WaranteeDataObject Warantee {
            get {
                return this.WaranteeField;
            }
            set {
                if ((object.ReferenceEquals(this.WaranteeField, value) != true)) {
                    this.WaranteeField = value;
                    this.RaisePropertyChanged("Warantee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ProductsMyDemo.ServiceReference2.LoanDataObjectList Loans {
            get {
                return this.LoansField;
            }
            set {
                if ((object.ReferenceEquals(this.LoansField, value) != true)) {
                    this.LoansField = value;
                    this.RaisePropertyChanged("Loans");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractDataObject", Namespace="http://www.ByteartRetail.com/ContractDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class ContractDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> GuaranteeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DepositField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ReGuaranteeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<decimal> GuaranteeAmount {
            get {
                return this.GuaranteeAmountField;
            }
            set {
                if ((this.GuaranteeAmountField.Equals(value) != true)) {
                    this.GuaranteeAmountField = value;
                    this.RaisePropertyChanged("GuaranteeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<decimal> Deposit {
            get {
                return this.DepositField;
            }
            set {
                if ((this.DepositField.Equals(value) != true)) {
                    this.DepositField = value;
                    this.RaisePropertyChanged("Deposit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> ReGuarantee {
            get {
                return this.ReGuaranteeField;
            }
            set {
                if ((this.ReGuaranteeField.Equals(value) != true)) {
                    this.ReGuaranteeField = value;
                    this.RaisePropertyChanged("ReGuarantee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> Ratio {
            get {
                return this.RatioField;
            }
            set {
                if ((this.RatioField.Equals(value) != true)) {
                    this.RatioField = value;
                    this.RaisePropertyChanged("Ratio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string ContractNo {
            get {
                return this.ContractNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNoField, value) != true)) {
                    this.ContractNoField = value;
                    this.RaisePropertyChanged("ContractNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WaranteeDataObject", Namespace="http://www.ByteartRetail.com/WaranteeDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class WaranteeDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LoanDataObjectList", Namespace="http://www.ByteartRetail.com/CollectionDataObjectList.xsd", ItemName="LoanDataObject")]
    [System.SerializableAttribute()]
    public class LoanDataObjectList : System.Collections.Generic.List<ProductsMyDemo.ServiceReference2.LoanDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanDataObject", Namespace="http://www.ByteartRetail.com/LoanDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class LoanDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ApplyLoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsMyDemo.ServiceReference2.CommonCodeDataObject DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ProductsMyDemo.ServiceReference2.LoanConfirmationStatusDataObject> LoanConfirmationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ProductsMyDemo.ServiceReference2.RelieveStatusDataObject> RelieveStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsMyDemo.ServiceReference2.LoanConfirmationDataObjectList LoanConfirmationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsMyDemo.ServiceReference2.LoanRelieveDataObjectList LoanRelievesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<decimal> ApplyLoanAmount {
            get {
                return this.ApplyLoanAmountField;
            }
            set {
                if ((this.ApplyLoanAmountField.Equals(value) != true)) {
                    this.ApplyLoanAmountField = value;
                    this.RaisePropertyChanged("ApplyLoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ContractNumber {
            get {
                return this.ContractNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractNumberField, value) != true)) {
                    this.ContractNumberField = value;
                    this.RaisePropertyChanged("ContractNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ProductsMyDemo.ServiceReference2.CommonCodeDataObject Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectionField, value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<ProductsMyDemo.ServiceReference2.LoanConfirmationStatusDataObject> LoanConfirmationStatus {
            get {
                return this.LoanConfirmationStatusField;
            }
            set {
                if ((this.LoanConfirmationStatusField.Equals(value) != true)) {
                    this.LoanConfirmationStatusField = value;
                    this.RaisePropertyChanged("LoanConfirmationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<ProductsMyDemo.ServiceReference2.RelieveStatusDataObject> RelieveStatus {
            get {
                return this.RelieveStatusField;
            }
            set {
                if ((this.RelieveStatusField.Equals(value) != true)) {
                    this.RelieveStatusField = value;
                    this.RaisePropertyChanged("RelieveStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public ProductsMyDemo.ServiceReference2.LoanConfirmationDataObjectList LoanConfirmations {
            get {
                return this.LoanConfirmationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanConfirmationsField, value) != true)) {
                    this.LoanConfirmationsField = value;
                    this.RaisePropertyChanged("LoanConfirmations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public ProductsMyDemo.ServiceReference2.LoanRelieveDataObjectList LoanRelieves {
            get {
                return this.LoanRelievesField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanRelievesField, value) != true)) {
                    this.LoanRelievesField = value;
                    this.RaisePropertyChanged("LoanRelieves");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonCodeDataObject", Namespace="http://www.ByteartRetail.com/CommonCodeDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class CommonCodeDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ProductsMyDemo.ServiceReference2.CommonStatusDataObject> CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<ProductsMyDemo.ServiceReference2.CommonStatusDataObject> Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<int> Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanConfirmationStatusDataObject", Namespace="http://www.ByteartRetail.com/LoanConfirmationStatusDataObject.xsd")]
    public enum LoanConfirmationStatusDataObject : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaitConfirm = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoLoan = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompleteConfirm = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartConfirm = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelieveStatusDataObject", Namespace="http://www.ByteartRetail.com/RelieveStatusDataObject.xsd")]
    public enum RelieveStatusDataObject : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnRelieve = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartRelieve = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CompleteRelieve = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SubrogationRelieve = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LoanConfirmationDataObjectList", Namespace="http://www.ByteartRetail.com/CollectionDataObjectList.xsd", ItemName="LoanConfirmationDataObject")]
    [System.SerializableAttribute()]
    public class LoanConfirmationDataObjectList : System.Collections.Generic.List<ProductsMyDemo.ServiceReference2.LoanConfirmationDataObject> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LoanRelieveDataObjectList", Namespace="http://www.ByteartRetail.com/CollectionDataObjectList.xsd", ItemName="LoanRelieveDataObject")]
    [System.SerializableAttribute()]
    public class LoanRelieveDataObjectList : System.Collections.Generic.List<ProductsMyDemo.ServiceReference2.LoanRelieveDataObject> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonStatusDataObject", Namespace="http://www.ByteartRetail.com/CommonStatusDataObject.xsd")]
    public enum CommonStatusDataObject : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeType = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayType = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayStatus = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayOption = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PayFre = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessType = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GuaranteeType = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Status = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CreditorType = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WarranteeType = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CGManType = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CGType = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContractStatus = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GoMark = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BQStatus = 14,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanConfirmationDataObject", Namespace="http://www.ByteartRetail.com/LoanConfirmationDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class LoanConfirmationDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ConfirmDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<decimal> LoanAmount {
            get {
                return this.LoanAmountField;
            }
            set {
                if ((this.LoanAmountField.Equals(value) != true)) {
                    this.LoanAmountField = value;
                    this.RaisePropertyChanged("LoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.DateTime> ConfirmDate {
            get {
                return this.ConfirmDateField;
            }
            set {
                if ((this.ConfirmDateField.Equals(value) != true)) {
                    this.ConfirmDateField = value;
                    this.RaisePropertyChanged("ConfirmDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanRelieveDataObject", Namespace="http://www.ByteartRetail.com/LoanRelieveDataObject.xsd")]
    [System.SerializableAttribute()]
    public partial class LoanRelieveDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RelieveAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RelieveDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RelieveAmount {
            get {
                return this.RelieveAmountField;
            }
            set {
                if ((this.RelieveAmountField.Equals(value) != true)) {
                    this.RelieveAmountField = value;
                    this.RaisePropertyChanged("RelieveAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RelieveDate {
            get {
                return this.RelieveDateField;
            }
            set {
                if ((this.RelieveDateField.Equals(value) != true)) {
                    this.RelieveDateField = value;
                    this.RaisePropertyChanged("RelieveDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
    [System.SerializableAttribute()]
    public partial class FaultData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FullMessage {
            get {
                return this.FullMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FullMessageField, value) != true)) {
                    this.FullMessageField = value;
                    this.RaisePropertyChanged("FullMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://www.ByteartRetail.com/QuerySpec.xsd")]
    [System.SerializableAttribute()]
    public partial class Pagination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProjectDataObjectListWithPagination", Namespace="http://www.ByteartRetail.com/CollectionDataObjectList.xsd")]
    [System.SerializableAttribute()]
    public partial class ProjectDataObjectListWithPagination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsMyDemo.ServiceReference2.Pagination PaginationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductsMyDemo.ServiceReference2.ProjectDataObjectList ProjectDataObjectListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductsMyDemo.ServiceReference2.Pagination Pagination {
            get {
                return this.PaginationField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginationField, value) != true)) {
                    this.PaginationField = value;
                    this.RaisePropertyChanged("Pagination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductsMyDemo.ServiceReference2.ProjectDataObjectList ProjectDataObjectList {
            get {
                return this.ProjectDataObjectListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectDataObjectListField, value) != true)) {
                    this.ProjectDataObjectListField = value;
                    this.RaisePropertyChanged("ProjectDataObjectList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ByteartRetail.com", ConfigurationName="ServiceReference2.IProjectService")]
    public interface IProjectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ByteartRetail.com/IProjectService/CreatProjects", ReplyAction="http://www.ByteartRetail.com/IProjectService/CreatProjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsMyDemo.ServiceReference2.FaultData), Action="http://www.ByteartRetail.com/IProjectService/CreatProjectsFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
        ProductsMyDemo.ServiceReference2.ProjectDataObjectList CreatProjects(ProductsMyDemo.ServiceReference2.ProjectDataObjectList projectDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ByteartRetail.com/IProjectService/UpdateProjects", ReplyAction="http://www.ByteartRetail.com/IProjectService/UpdateProjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsMyDemo.ServiceReference2.FaultData), Action="http://www.ByteartRetail.com/IProjectService/UpdateProjectsFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
        ProductsMyDemo.ServiceReference2.ProjectDataObjectList UpdateProjects(ProductsMyDemo.ServiceReference2.ProjectDataObjectList projectDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ByteartRetail.com/IProjectService/GetProjectByKey", ReplyAction="http://www.ByteartRetail.com/IProjectService/GetProjectByKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsMyDemo.ServiceReference2.FaultData), Action="http://www.ByteartRetail.com/IProjectService/GetProjectByKeyFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
        ProductsMyDemo.ServiceReference2.ProjectDataObject GetProjectByKey(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ByteartRetail.com/IProjectService/GetProjectByProjectNo", ReplyAction="http://www.ByteartRetail.com/IProjectService/GetProjectByProjectNoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsMyDemo.ServiceReference2.FaultData), Action="http://www.ByteartRetail.com/IProjectService/GetProjectByProjectNoFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
        ProductsMyDemo.ServiceReference2.ProjectDataObject GetProjectByProjectNo(string projectNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ByteartRetail.com/IProjectService/GetProjects", ReplyAction="http://www.ByteartRetail.com/IProjectService/GetProjectsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsMyDemo.ServiceReference2.FaultData), Action="http://www.ByteartRetail.com/IProjectService/GetProjectsFaultDataFault", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
        ProductsMyDemo.ServiceReference2.ProjectDataObjectList GetProjects(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ByteartRetail.com/IProjectService/GetProjectsByWaranteeName", ReplyAction="http://www.ByteartRetail.com/IProjectService/GetProjectsByWaranteeNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsMyDemo.ServiceReference2.FaultData), Action="http://www.ByteartRetail.com/IProjectService/GetProjectsByWaranteeNameFaultDataFa" +
            "ult", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
        ProductsMyDemo.ServiceReference2.ProjectDataObjectList GetProjectsByWaranteeName(string WaranteeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ByteartRetail.com/IProjectService/GetProjectByContractNo", ReplyAction="http://www.ByteartRetail.com/IProjectService/GetProjectByContractNoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsMyDemo.ServiceReference2.FaultData), Action="http://www.ByteartRetail.com/IProjectService/GetProjectByContractNoFaultDataFault" +
            "", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
        ProductsMyDemo.ServiceReference2.ProjectDataObject GetProjectByContractNo(string contractNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ByteartRetail.com/IProjectService/GetProjectsWithPagination", ReplyAction="http://www.ByteartRetail.com/IProjectService/GetProjectsWithPaginationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ProductsMyDemo.ServiceReference2.FaultData), Action="http://www.ByteartRetail.com/IProjectService/GetProjectsWithPaginationFaultDataFa" +
            "ult", Name="FaultData", Namespace="http://schemas.datacontract.org/2004/07/LAFAFGS.DataObjects")]
        ProductsMyDemo.ServiceReference2.ProjectDataObjectListWithPagination GetProjectsWithPagination(ProductsMyDemo.ServiceReference2.Pagination pagination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectServiceChannel : ProductsMyDemo.ServiceReference2.IProjectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectServiceClient : System.ServiceModel.ClientBase<ProductsMyDemo.ServiceReference2.IProjectService>, ProductsMyDemo.ServiceReference2.IProjectService {
        
        public ProjectServiceClient() {
        }
        
        public ProjectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProductsMyDemo.ServiceReference2.ProjectDataObjectList CreatProjects(ProductsMyDemo.ServiceReference2.ProjectDataObjectList projectDataObjects) {
            return base.Channel.CreatProjects(projectDataObjects);
        }
        
        public ProductsMyDemo.ServiceReference2.ProjectDataObjectList UpdateProjects(ProductsMyDemo.ServiceReference2.ProjectDataObjectList projectDataObjects) {
            return base.Channel.UpdateProjects(projectDataObjects);
        }
        
        public ProductsMyDemo.ServiceReference2.ProjectDataObject GetProjectByKey(System.Guid id) {
            return base.Channel.GetProjectByKey(id);
        }
        
        public ProductsMyDemo.ServiceReference2.ProjectDataObject GetProjectByProjectNo(string projectNo) {
            return base.Channel.GetProjectByProjectNo(projectNo);
        }
        
        public ProductsMyDemo.ServiceReference2.ProjectDataObjectList GetProjects(int count) {
            return base.Channel.GetProjects(count);
        }
        
        public ProductsMyDemo.ServiceReference2.ProjectDataObjectList GetProjectsByWaranteeName(string WaranteeName) {
            return base.Channel.GetProjectsByWaranteeName(WaranteeName);
        }
        
        public ProductsMyDemo.ServiceReference2.ProjectDataObject GetProjectByContractNo(string contractNo) {
            return base.Channel.GetProjectByContractNo(contractNo);
        }
        
        public ProductsMyDemo.ServiceReference2.ProjectDataObjectListWithPagination GetProjectsWithPagination(ProductsMyDemo.ServiceReference2.Pagination pagination) {
            return base.Channel.GetProjectsWithPagination(pagination);
        }
    }
}
